import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Nav from "@/components/Nav/Nav";
import Footers from "@/components/Footers/Footers";
import { getDictionary } from "../dictionaries";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
   props: Readonly<{
    children: React.ReactNode;
    params: Promise<{ lang: string }>; // `params` should be a promise
  }>
){
  const params = await props.params;

  const { children } = props;

  const lang = await getDictionary(params.lang);
  return (
    <html lang={lang} className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav lang={lang}/>
        {children}
        <Footers lang={lang}/>
      </body>
    </html>
  );
}
